### ISSUE TITLE
How to set database user (documentation issue/need information)

### ISSUE THREAD

**Issue by nikkov** [transceptor-technology/siridb-http#15]
Hi,
I want to try siridb in action, but I can't start siridb-http, because I can't find any information in tools description on how to create a database user.

My steps:
1. I installed the siridb-server
2. I Created a database and additional service account from siridb-admin
3. I'm trying to run sirib-http but I'm "not authenticated"

As I understand I need to create a database user and set one in config, but with what tool I can create? Siridb-admin doesn't allow this, but without database user it is impossible to connect siridb-http.
Can you describe how to create database user?

Thank you!

**Comment by joente** [comment]
A new database will have the default user `iris` with password `siri`.

With this username/password you can use [siridb-http](https://github.com/transceptor-technology/siridb-http#readme) or [siridb-prompt](https://github.com/transceptor-technology/siridb-http#readme) to connect to the database and create other database users.

Documentation on how to create additional users can be found here: [http://siridb.net/docs/#help_create_user](http://siridb.net/docs/#help_create_user)

ps. I've changed the documentation of SiriDB Admin and added a note for the default user/password at the *new database* section.
